# Generated by Django 4.2.7 on 2023-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_duration_location_rename_price_product_m_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='m_price',
            field=models.IntegerField(null=True),
        ),
    ]
