# Generated by Django 4.2.7 on 2023-12-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='memory',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
    ]
