# Generated by Django 4.2.7 on 2023-12-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_memory_product_plan_remove_product_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='m_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.CharField(choices=[('Micro Business Plan', 'Micro Business Plan'), ('Small Business Plan', 'Small Business Plan'), ('Medium Business Plan', 'Medium Business Plan'), ('Aditional Products', 'Aditional Products')], default='None', max_length=25),
        ),
    ]
